version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: ec2-50-19-109-120.compute-1.amazonaws.com
            database: de293km3js7o9c
            user: ygrbgigbpnjyht
            ssl: true
            password: e8248caf4b949bcf91b32b07157b8872d02b8cc5173863d9bab123c8dccbf025
            rawAccess: true
            port: '5432'
            migrations: true