version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.28
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: ec2-54-243-228-140.compute-1.amazonaws.com
            database: df96e1q6g9m3v8
            user: huwyxgkuhgmvou
            ssl: true
            password: 65a4ad8ee3c1b4e5556fb0bb151325fb26d69e13020eb6090c44e3b5d5b4da54
            rawAccess: true
            port: '5432'
            migrations: true