export const SET_AUTH_COMPLETED = 'SET_AUTH_COMPLETED'
export const SET_AUTH = 'SET_AUTH'
export const CLEAR_TOKEN_RENEWAL_TIMEOUT = 'CLEAR_TOKEN_RENEWAL_TIMEOUT'

export const SET_USER = 'SET_USER'
export const RESET_USER = 'RESET_USER'
export const UPDATE_USER = 'UPDATE_USER'

export const SET_PROJECTS = 'SET_PROJECTS'
export const CREATE_PROJECT = 'SET_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const DELETE_PROJECT = 'UPDATE_PROJECT'

export const SET_SUBSCRIBERS = 'SET_SUBSCRIBERS'
export const CREATE_SUBSCRIBER = 'CREATE_SUBSCRIBER'
export const UPDATE_SUBSCRIBER = 'UPDATE_SUBSCRIBER'
export const DELETE_SUBSCRIBER = 'DELETE_SUBSCRIBER'

export const SET_MILESTONES = 'SET_MILESTONES'
export const CREATE_MILESTONE = 'CREATE_MILESTONE'
export const UPDATE_MILESTONE = 'UPDATE_MILESTONE'
export const DELETE_MILESTONE = 'DELETE_MILESTONE'